### ISSUE TITLE
Is this code any use to anyone else?

### ISSUE THREAD

**Issue by davidread** [opendatamonitor/ckanext-harvestodm#2]
It would be good to hear more about what you've 'extended' in the CKAN harvest infrastructure here. Could any of these publicly funded enhancements be useful to anyone else? It would be good to get the ball rolling with a discussion here or on ckan-dev, otherwise I fear any good bits in this repo will be ignored and lost to the community.

**Comment by vkaff** [comment]
These were some adjustments and modifications for the purpose of using it in the context of the ODM project. We have added a list of the main modifications in the updated README file.

**Comment by davidread** [comment]
Thanks, this is really helpful to have a clear README.

I think many of these things would be useful to contribute back from your fork - there are many initiatives of harvesting across multiple countries, not least the Pan-European Portal (which is also EU funded). There are lots of things here that would be good to have in ckanext-harvest - e.g. recording language and country, harmonization etc. So it would be good if you worked with the community to agree how we should do all these things commonly and then everyone can benefit from avoiding duplicating this work.
